# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.position import Position  # noqa: E501
from swagger_client.rest import ApiException


class TestPosition(unittest.TestCase):
    """Position unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPosition(self):
        """Test Position"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.position.Position()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
