# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.spawn_map_object import SpawnMapObject  # noqa: E501
from swagger_client.rest import ApiException


class TestSpawnMapObject(unittest.TestCase):
    """SpawnMapObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpawnMapObject(self):
        """Test SpawnMapObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.spawn_map_object.SpawnMapObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
