# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_d_elete_api_world_objects_id(self):
        """Test case for d_elete_api_world_objects_id

        """
        pass

    def test_g_et_api_player(self):
        """Test case for g_et_api_player

        """
        pass

    def test_g_et_api_world(self):
        """Test case for g_et_api_world

        """
        pass

    def test_g_et_api_world_doors(self):
        """Test case for g_et_api_world_doors

        """
        pass

    def test_g_et_api_world_doors_id(self):
        """Test case for g_et_api_world_doors_id

        """
        pass

    def test_g_et_api_world_objects(self):
        """Test case for g_et_api_world_objects

        """
        pass

    def test_g_et_api_world_objects_id(self):
        """Test case for g_et_api_world_objects_id

        """
        pass

    def test_p_atch_api_player(self):
        """Test case for p_atch_api_player

        """
        pass

    def test_p_atch_api_world(self):
        """Test case for p_atch_api_world

        """
        pass

    def test_p_atch_api_world_doors_id(self):
        """Test case for p_atch_api_world_doors_id

        """
        pass

    def test_p_atch_api_world_objects_id(self):
        """Test case for p_atch_api_world_objects_id

        """
        pass

    def test_p_ost_api_player_actions(self):
        """Test case for p_ost_api_player_actions

        """
        pass

    def test_p_ost_api_world_objects(self):
        """Test case for p_ost_api_world_objects

        """
        pass


if __name__ == '__main__':
    unittest.main()
