# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.player_key_cards import PlayerKeyCards  # noqa: E501
from swagger_client.rest import ApiException


class TestPlayerKeyCards(unittest.TestCase):
    """PlayerKeyCards unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerKeyCards(self):
        """Test PlayerKeyCards"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.player_key_cards.PlayerKeyCards()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
