# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.position1 import Position1  # noqa: E501
from swagger_client.rest import ApiException


class TestPosition1(unittest.TestCase):
    """Position1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPosition1(self):
        """Test Position1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.position1.Position1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
