# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PlayerKeyCards(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blue': 'bool',
        'red': 'bool',
        'yellow': 'bool'
    }

    attribute_map = {
        'blue': 'blue',
        'red': 'red',
        'yellow': 'yellow'
    }

    def __init__(self, blue=None, red=None, yellow=None):  # noqa: E501
        """PlayerKeyCards - a model defined in Swagger"""  # noqa: E501

        self._blue = None
        self._red = None
        self._yellow = None
        self.discriminator = None

        self.blue = blue
        self.red = red
        self.yellow = yellow

    @property
    def blue(self):
        """Gets the blue of this PlayerKeyCards.  # noqa: E501


        :return: The blue of this PlayerKeyCards.  # noqa: E501
        :rtype: bool
        """
        return self._blue

    @blue.setter
    def blue(self, blue):
        """Sets the blue of this PlayerKeyCards.


        :param blue: The blue of this PlayerKeyCards.  # noqa: E501
        :type: bool
        """
        if blue is None:
            raise ValueError("Invalid value for `blue`, must not be `None`")  # noqa: E501

        self._blue = blue

    @property
    def red(self):
        """Gets the red of this PlayerKeyCards.  # noqa: E501


        :return: The red of this PlayerKeyCards.  # noqa: E501
        :rtype: bool
        """
        return self._red

    @red.setter
    def red(self, red):
        """Sets the red of this PlayerKeyCards.


        :param red: The red of this PlayerKeyCards.  # noqa: E501
        :type: bool
        """
        if red is None:
            raise ValueError("Invalid value for `red`, must not be `None`")  # noqa: E501

        self._red = red

    @property
    def yellow(self):
        """Gets the yellow of this PlayerKeyCards.  # noqa: E501


        :return: The yellow of this PlayerKeyCards.  # noqa: E501
        :rtype: bool
        """
        return self._yellow

    @yellow.setter
    def yellow(self, yellow):
        """Sets the yellow of this PlayerKeyCards.


        :param yellow: The yellow of this PlayerKeyCards.  # noqa: E501
        :type: bool
        """
        if yellow is None:
            raise ValueError("Invalid value for `yellow`, must not be `None`")  # noqa: E501

        self._yellow = yellow

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlayerKeyCards, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlayerKeyCards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
