# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PlayerCheatFlags(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cf_godmode': 'bool',
        'cf_no_clip': 'bool'
    }

    attribute_map = {
        'cf_godmode': 'CF_GODMODE',
        'cf_no_clip': 'CF_NO_CLIP'
    }

    def __init__(self, cf_godmode=None, cf_no_clip=None):  # noqa: E501
        """PlayerCheatFlags - a model defined in Swagger"""  # noqa: E501

        self._cf_godmode = None
        self._cf_no_clip = None
        self.discriminator = None

        if cf_godmode is not None:
            self.cf_godmode = cf_godmode
        if cf_no_clip is not None:
            self.cf_no_clip = cf_no_clip

    @property
    def cf_godmode(self):
        """Gets the cf_godmode of this PlayerCheatFlags.  # noqa: E501


        :return: The cf_godmode of this PlayerCheatFlags.  # noqa: E501
        :rtype: bool
        """
        return self._cf_godmode

    @cf_godmode.setter
    def cf_godmode(self, cf_godmode):
        """Sets the cf_godmode of this PlayerCheatFlags.


        :param cf_godmode: The cf_godmode of this PlayerCheatFlags.  # noqa: E501
        :type: bool
        """

        self._cf_godmode = cf_godmode

    @property
    def cf_no_clip(self):
        """Gets the cf_no_clip of this PlayerCheatFlags.  # noqa: E501


        :return: The cf_no_clip of this PlayerCheatFlags.  # noqa: E501
        :rtype: bool
        """
        return self._cf_no_clip

    @cf_no_clip.setter
    def cf_no_clip(self, cf_no_clip):
        """Sets the cf_no_clip of this PlayerCheatFlags.


        :param cf_no_clip: The cf_no_clip of this PlayerCheatFlags.  # noqa: E501
        :type: bool
        """

        self._cf_no_clip = cf_no_clip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlayerCheatFlags, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlayerCheatFlags):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
