# coding: utf-8

"""
    RESTful-DOOM

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class World(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'episode': 'int',
        'map': 'int'
    }

    attribute_map = {
        'episode': 'episode',
        'map': 'map'
    }

    def __init__(self, episode=None, map=None):  # noqa: E501
        """World - a model defined in Swagger"""  # noqa: E501

        self._episode = None
        self._map = None
        self.discriminator = None

        if episode is not None:
            self.episode = episode
        if map is not None:
            self.map = map

    @property
    def episode(self):
        """Gets the episode of this World.  # noqa: E501

        The current episode  # noqa: E501

        :return: The episode of this World.  # noqa: E501
        :rtype: int
        """
        return self._episode

    @episode.setter
    def episode(self, episode):
        """Sets the episode of this World.

        The current episode  # noqa: E501

        :param episode: The episode of this World.  # noqa: E501
        :type: int
        """

        self._episode = episode

    @property
    def map(self):
        """Gets the map of this World.  # noqa: E501

        The current map  # noqa: E501

        :return: The map of this World.  # noqa: E501
        :rtype: int
        """
        return self._map

    @map.setter
    def map(self, map):
        """Sets the map of this World.

        The current map  # noqa: E501

        :param map: The map of this World.  # noqa: E501
        :type: int
        """

        self._map = map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(World, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, World):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
